import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidbar";
import Layout from "@/components/Layout";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "E-Commerce-Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Layout>
          <div className="sticky top-0 z-50">
            <Header />
          </div>
          <div className="flex">
            {/* Sticky Sidebar */}
            <div className="sticky top-[97px] h-[calc(100vh-80px)]  z-40 hidden md:block">
              <Sidebar />
            </div>
            {/* Main content */}
            <div className="flex-1">
              {children}
              {/* <Footer /> */}
            </div>
          </div>
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </Layout>

      </body>
    </html>
  );
}
